# Lab 2: Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices. 

## 1. Example

### 1.1 Load data with pandas

In [1]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [2]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [32]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [118]:
# this is your code to get two vectors
c1 = X[:,[0]]
c2 = X[:,[-1]]
print(c1[0:5])
print(c2[0:5])

[[18.0]
 [15.0]
 [18.0]
 [16.0]
 [17.0]]
[[70]
 [70]
 [70]
 [70]
 [70]]


### 2.2 Perform following operations on these two vectors and print the result

In [120]:
# 1. addition and subtraction
result_add = c1 + c2
# print(result_add)

# 2. element-wise multiplication
result_elem_wise = np.multiply(c1, c2)
# print(result_elem_wise)

# 3. inner product
result_inner = np.inner(c1, c2)
print(result_inner)
print(result_inner.shape)

# 4. three norms
l1 = np.linalg.norm(c1, ord=1)
l2 = np.linalg.norm(c1, ord=1)
max_norm = np.linalg.norm(c1 ,ord=np.inf)

print(f"l1: {l1}")
print(f"l2: {l2}")
print(f"max_norm: {max_norm}")

# 5. compute the distance between these two vectors
distance = np.linalg.norm(c1-c2, ord=1)
print(f"distance: {distance}")

[[1260.0 1260.0 1260.0 ... 1476.0 1476.0 1476.0]
 [1050.0 1050.0 1050.0 ... 1230.0 1230.0 1230.0]
 [1260.0 1260.0 1260.0 ... 1476.0 1476.0 1476.0]
 ...
 [2240.0 2240.0 2240.0 ... 2624.0 2624.0 2624.0]
 [1960.0 1960.0 1960.0 ... 2296.0 2296.0 2296.0]
 [2170.0 2170.0 2170.0 ... 2542.0 2542.0 2542.0]]
(406, 406)
l1: 9358.800000000003
l2: 9358.800000000003
max_norm: 46.6
distance: 21465.199999999993


### 2.3 Get the first three columns and the last three columns from X

In [74]:
# this is your code to get two matrices: A, B
print(X)

[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


In [94]:
A = X[:,0:3]
B = X[:,-3:]

### 2.4 Perform following operations on these two matrices and print the result

In [117]:
# 1. addition and subtraction
result_sum = A + B
print(result_sum)

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = np.transpose(B)
print(f"C shape: {C.shape}")

# 3. compute the product between A and C, and print the result and its shape
result_product = np.matmul(C, A)
print(f"result_product: {result_product}")
print(f"result_product shape: {result_product.shape}")

# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = np.transpose(A)


# 5. compute the product between D and B, and print the result and its shape
result_product2 = np.matmul(D, B)
print(f"result_product2: {result_product2}")
print(f"result_product2 shape: {result_product2.shape}")

[[3522.0 20.0 377.0]
 [3708.0 19.5 420.0]
 [3454.0 19.0 388.0]
 ...
 [2327.0 15.6 217.0]
 [2653.0 22.6 202.0]
 [2751.0 23.4 201.0]]
C shape: (3, 406)
result_product: [[25614040.900000002 7149030 269175402.0]
 [149295.04000000004 33484.69999999997 1160836.2999999998]
 [718009.0999999995 167835 5943079.0]]
result_product shape: (3, 3)
result_product2: [[25614040.900000002 149295.04000000004 718009.0999999995]
 [7149030 33484.69999999997 167835]
 [269175402.0 1160836.2999999998 5943079.0]]
result_product2 shape: (3, 3)
